# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "precise64"

  config.vm.box_url = "http://files.vagrantup.com/precise64.box"

  # Make the name show up as aku in virtualbox
  config.vm.provider "virtualbox" do |p|
      p.name = "saclug"
  end
  config.vm.define :saclug do |t|
  end

  # Forward port 80 => 8000 on the host
  config.vm.network "forwarded_port", guest: 8000, host: 8000

  # Share folders
  config.vm.synced_folder "../", "/srv/saclug"

  # Puppet file path
  config.vm.provision :puppet do |puppet|
    puppet.manifests_path = "manifests"
    puppet.manifest_file  = "init.pp"
  end
end
